name: publish
version:  0.2.2
synopsis: Publishing tools for papers, books, and presentations
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2016-2018 Operational Dynamics Consulting Pty Ltd, and Others
category: Text
tested-with: GHC == 8.4

dependencies:
 - base
 - bytestring
 - chronologique
 - directory
 - filepath
 - hinotify
 - pandoc-types
 - pandoc
 - text
 - typed-process
 - unbeliever >= 0.6
 - unix
 - unordered-containers

ghc-options: -threaded -Wall -Wwarn -fwarn-tabs

executables:
  render:
    source-dirs: src
    main: RenderMain.hs
    other-modules:
     - RenderDocument
     - Environment
     - LatexPreamble
     - NotifyChanges
     - OutputParser
     - Paths_publish
     - Utilities
