name: publish
version:  0.3.2
synopsis: Publishing tools for papers, books, and presentations
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2016-2018 Operational Dynamics Consulting Pty Ltd, and Others
category: Text
tested-with: GHC == 8.4

dependencies:
 - base
 - bytestring
 - chronologique
 - directory
 - filepath
 - hinotify
 - pandoc-types
 - pandoc
 - template-haskell
 - text
 - typed-process
 - unbeliever >= 0.7.2
 - unix
 - unordered-containers

ghc-options: -threaded -Wall -Wwarn -fwarn-tabs

executables:
  render:
    source-dirs: src
    main: RenderMain.hs
    other-modules:
     - RenderDocument
     - Environment
     - LatexPreamble
     - NotifyChanges
     - OutputParser
     - Paths_publish
     - Utilities

  format:
    source-dirs: src
    main: FormatMain.hs
    other-modules:
     - FormatDocument

tests:
  experiment:
    dependencies:
     - unbeliever
    source-dirs:
     - tests
     - src
    main: ReformatTest.hs
    other-modules:
     - FormatDocument
     - PandocToMarkdown

  check:
    dependencies:
     - hspec
    ghc-options: -threaded
    source-dirs:
     - src
     - tests
    main: TestSuite.hs
    other-modules:
     - CompareFragments


