name: publish
version:  0.4.3
synopsis: Publishing tools for papers, books, and presentations
description: |
  Tools for rendering markdown-centric documents into PDFs.
  
  A description of this package, a list of features, and some background
  to its design is contained in the
  <https://github.com/oprdyn/publish/blob/master/README.markdown README>
  on GitHub.
  
  The main program, @render@, is available via a Docker image at
  <https://cloud.docker.com/u/oprdyn/repository/docker/oprdyn/publish-render/general docker.io/oprdyn/publish-render:latest>

stability: experimental
license: BSD3
license-file: LICENCE
author: Andrew Cowie <andrew@operationaldynamics.com>
maintainer: Andrew Cowie <andrew@operationaldynamics.com>
copyright: © 2016-2019 Operational Dynamics Consulting Pty Ltd, and Others
category: Text
tested-with: GHC == 8.6
github: oprdyn/publish

dependencies:
 - base >= 4.11 && < 5
 - bytestring
 - chronologique
 - deepseq
 - directory
 - filepath
 - hinotify
 - pandoc-types
 - pandoc
 - template-haskell
 - text
 - typed-process
 - unbeliever >= 0.9.3.2
 - unix
 - unordered-containers

ghc-options: -threaded -Wall -Wwarn -fwarn-tabs

executables:
  render:
    source-dirs: src
    main: RenderMain.hs
    other-modules:
     - Environment
     - LatexPreamble
     - NotifyChanges
     - OutputParser
     - PandocToMarkdown
     - RenderDocument
     - Utilities

  format:
    source-dirs: src
    main: FormatMain.hs
    other-modules:
     - FormatDocument
     - PandocToMarkdown

tests:
  check:
    dependencies:
     - hspec
    ghc-options: -threaded
    source-dirs:
     - src
     - tests
    main: TestSuite.hs
    other-modules:
     - CheckTableProperties
     - CompareFragments
     - FormatDocument
     - PandocToMarkdown


