resolver: lts-11.13
packages:
 - .
extra-deps:
 - /home/andrew/vcs/haskell/pandoc-types
 - /home/andrew/vcs/haskell/pandoc
 - haddock-library-1.6.0
 - skylighting-0.7.2
 - skylighting-core-0.7.2
 - texmath-0.11.0.1


