resolver: lts-14.8
packages:
 - .

extra-deps:
 - git: http://github.com/oprdyn/unbeliever
   commit: de7cfc43b4a1572a204125b1f822f22b201089f8
   subdirs:
    - core-text
    - core-program
    - core-data

